name: Run Telegram Bot Daily

on:
  schedule:
    - cron: "0 9 * * *"  # Запуск каждый день в 9:00 UTC (по Москве 12:00)
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install aiogram

      - name: Run bot script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py
